# Generated by Django 4.0.3 on 2022-06-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
